name: CI implementacion App

on:
  push: 
    branches: [main, develop ]

env:
  REGISTRY: ghcr.io

jobs:
  services-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v5

    # --- Test de Vote ---
    - name: Configurar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Instalar requisitos 
      run: |
        pip install -r ./vote/requirements.txt
    
    - name: Test Vote
      run: |
        pytest ./vote/tests/ -v

    # --- Test de Worker && Result ---
    - name: Configurar Node
      uses: actions/setup-node@v6
      with:
        node-version: '18.19.1'

    - name: Instalar paquetes
      run: |
        npm install --prefix ./worker

    - name: Test Worker
      run: |
        npm test --prefix ./worker

    - name: Instalar paquetes
      run: |
        npm install --prefix ./result

    - name: Test Result
      run: |
        npm test --prefix ./result
  
  integration-tests:
    runs-on: ubuntu-latest
    needs: services-tests
    
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v5

      - name: Crear archivo .env
        run: |
          echo "REDIS_HOST=redis" > .env
          echo "REDIS_PORT=6379" >> .env
          echo "DATABASE_HOST=postgres" >> .env
          echo "DATABASE_USER=postgres" >> .env
          echo "DATABASE_PASSWORD=postgres" >> .env
          echo "DATABASE_NAME=votes" >> .env
      
      - name: Levantar servicios con Docker compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Esperar que los servicios esten operativos
        run: sleep 15

      - name: Probar el endpoint de vote
        run: |
          curl --fail http://localhost:80

      - name: Probar el endpoint de result
        run: |
          curl --fail http://localhost:3000

  build-and-push:
    runs-on: ubuntu-latest
    needs: integration-tests
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in Github Container
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and push vote app
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          push: true
          tags: ${{ env.REGISTRY }}/vicrounix/vote:latest

      - name: Build and push worker app
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: ${{ env.REGISTRY }}/vicrounix/worker:latest

      - name: Build and push result app
        uses: docker/build-push-action@v6
        with:
          context: ./result
          push: true
          tags: ${{ env.REGISTRY }}/vicrounix/result:latest
    