name: CI Vote App

on:
  push: [main, develop]

jobs:
  services-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v5

    # --- Test de Vote ---
    - name: Configurar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Instalar requisitos 
      run: |
        pip install -r ./vote/requirements.txt
    
    - name: Test Vote
      run: |
        pytest ./vote/tests/ -v

    # --- Test de Worker && Result ---
    - name: Configurar Node
      uses: actions/setup-node@v6
      with:
        node-version: '18.19.1'

    - name: Instalar paquetes
      run: |
        npm install --prefix ./worker

    - name: Test Worker
      run: |
        npm test --prefix ./worker

    - name: Instalar paquetes
      run: |
        npm install --prefix ./result

    - name: Test Result
      run: |
        npm test --prefix ./result
  
  integration-tests:
    runs-on: ubuntu-latest
    needs: services-tests
    
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v5

      - name: Crear archivo .env
        run: |
          echo "REDIS_HOST=redis" > .env
          echo "REDIS_PORT=6379" >> .env
          echo "DATABASE_HOST=postgres" >> .env
          echo "DATABASE_USER=postgres" >> .env
          echo "DATABASE_PASSWORD=postgres" >> .env
          echo "DATABASE_NAME=votes" >> .env
      
      - name: Levantar servicios con Docker compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Esperar que los servicios esten operativos
        run: sleep 15

      - name: Probar el endpoint de vote
        run: |
          curl --fail http://localhost:80

      - name: Probar el endpoint de result
        run: |
          curl --fail http://localhost:3000

    